spring:
  application:
    name: wcc-backend
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/wcc
    username: postgres
    password: MFpFnhhICniFNPA
    driver-class-name: org.postgresql.Driver

security:
  api:
    key: e8-Mm0ybormRil7k_DZO9jYtRAYW5VX5MCQiQG2CLD4

file:
  storage:
    directory: data

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
  paths-to-match: /api/**, /actuator/**

#  to deploy to DEV env update application-docker.yml
surrealdb:
  host: localhost
  port: 8000
  tls: false
  timeout-seconds: 60
  namespace: wcc
  database: platform
  username: root
  password: root


