spring:
  config:
    activate:
      on-profile: docker
  mail:
    properties:
      mail:
        smtp:
          enable: false
          auth: false
          starttls:
            enable: false

file:
  storage:
    directory: /app/data

logging:
  level:
    org:
      springframework:
        jdbc: WARN
      flywaydb: WARN