spring:
  application:
    name: wcc-backend
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/wcc
    username: postgres
    password: MFpFnhhICniFNPA
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false

mentorship:
  daysCycleOpen: 10

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
      flywaydb: DEBUG

security:
  enabled: true
  token:
    ttl-minutes: 60
  api:
    key: local

file:
  storage:
    directory: data

app:
  cors:
    allowed-origins: http://localhost:3000,https://localhost:3000
  seed:
    admin:
      enabled: true
      email: admin@wcc.dev
      password: wcc-admin

storage:
  type: local
  folders:
    main-folder: folder-id
    resources-folder: folder-id
    events-folder: folder-id
    mentors-folder: folder-id
    mentors-profile-folder: folder-id
    images-folder: folder-id

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,loggers"

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
  paths-to-match: /api/**, /actuator/**
