spring:
  application:
    name: wcc-backend
  profiles:
    active: default

file:
  storage:
    directory: data

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
  paths-to-match: /api/**

surrealdb:
  host: localhost
  port: 8000
  tls: false
  connections: 5
  namespace: wcc
  database: platform
  username: root
  password: root
